#!/bin/sh
# POSTINST script for wimsconstructioncam

echo "$(tput setaf 3) HI I'M A POSTINST SCRIPT `date +"%s"`$(tput sgr0)"
systemctl daemon-reload
systemctl enable wimsconstructioncam.service
systemctl start wimsconstructioncam.service

exit 0