#!/bin/sh
# PRERM script for wimsconstructioncam

echo "\033[36m HI I'M A PRERM SCRIPT `date +"%s"` \033[39m"
systemctl stop wimsconstructioncam.service
systemctl disable wimsconstructioncam.service

exit 0